/*
 * This source file was generated by the Gradle 'init' task
 */
package java_project;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import java.util.Scanner;

import frontend.Parser;
import frontend.ast.Program;
import runtime.Interpreter;
import runtime.Scope;

public class App {
  /**
   * run with no cmdline-args to access repl, or include a file to execute
   */
  public static void main(String[] args) {
    if (args.length == 1)
      runFile(args[0]);
    else
      repl();
  }

  private static void runFile(String fname) {
    Parser p = new Parser();
    Interpreter interpreter = new Interpreter();

    Scope globalScope = Scope.createGlobalScope();

    try {
      File f = new File(fname);
      Scanner s = new Scanner(f);
      String str = s.useDelimiter("\\Z").next();
      s.close();

      Program ast = p.createAST(str);
      interpreter.evaluate(ast, globalScope);
    } catch (FileNotFoundException e) {
      System.err.println("File " + fname + " not found. Exiting.");
    }

  }

  private static void repl() {
    System.out.println("========================================");
    System.out.println("               Repl v0.1                ");
    System.out.println("           Press 'q' to exit            ");
    System.out.println("========================================\n");

    Parser parser = new Parser();
    Interpreter interpreter = new Interpreter();
    Scanner s = new Scanner(System.in);
    Scope env = new Scope(null);

    // break with EOF (Ctrl+D)
    while (true) {
      System.out.print("> ");
      try {
        String input = s.nextLine();
        Program program = parser.createAST(input);
        System.out.println(interpreter.evaluate(program, env));
      } catch (NoSuchElementException e) {
        System.out.println("\n\nEOF found, shutting down repl.\n");
        break;
      }
    }
    s.close();
  }
}
