/*
 * This source file was generated by the Gradle 'init' task
 */
package java_project;

import java.util.Scanner;

import frontend.Parser;
import frontend.ast.Program;

public class App {
  public static void main(String[] args) {
    Parser p = new Parser();
    System.out.println("Repl v0.1");
    Scanner s = new Scanner(System.in);
    while (true) {
      System.out.print("> ");
      String input = s.nextLine();
      if (input.isBlank() || input.equals("exit")) {
        break;
      }
      Program program = p.createAST(input);
      program.print();
    }
    s.close();
  }
}
